version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  Circle CI:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Upgrade pip
          command: python3 -m pip install --upgrade pip
      - run:
          name: Create venv
          command: python3 -m venv venv
      - run:
          name: Enter venv
          command: source venv/bin/activate
      - run:
          name: Run pip install
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m pytest
