version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  Circle CI:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install deps
          command: apk add jpeg-dev
      - run: 
          name: Upgrade pip
          command: python3 -m pip install --upgrade pip
      - run:
          name: Enable venv 
          command: sudo pip install pipenv
      - run:
          name: Install venv
          command: pipenv install
      - run:
          name: Run pip install
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
